accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/<int:user_pk>', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:board_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('', views.index, name='index'),
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
        
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE) 
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'email',]

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash    # 비밀번호 변경 후 로그인 상태 유지
from django.contrib.auth import get_user_model
from .forms import UserCustomChangeForm, UserCustomCreationForm

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
        
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()              # 1
            auth_login(request, user)       # 2
            return redirect('boards:index')
    else:
        form = UserCustomCreationForm()
    context = {'form': form}
    return render(request, 'accounts/auth_form.html', context)
    
def login(request):
    if request.user.is_authenticated:       
        return redirect('boards:index')
        
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.POST.get('next') or 'boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
        'next': request.GET.get('next', ''),
    }
    return render(request, 'accounts/login.html', context)
    
def logout(request):
    auth_logout(request)
    return redirect('boards:index')

def delete(request):
    user = request.user
    if request.method == 'POST':
        # DELETE
        user.delete()
    return redirect('boards:index')
    
def edit(request):
    if request.method == 'POST':
        # UserChangeForm > UserCustomChangeForm
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    context = {'form': form,}
    return render(request, 'accounts/auth_form.html', context)
    
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)   # 인자 순서 유의
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)     # 비밀번호 변경 후에도 로그인 상태 유지
            return redirect('boards:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form,}
    return render(request, 'accounts/auth_form.html', context)

def profile(request, user_pk):
    user_info = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        'user_info': user_info,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/auth_form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'edit' %}
    <h1>회원수정</h1>
{% else %}
    <h1>비밀번호 변경</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
    <input type="hidden" value="{{ next }}", name="next"/>
</form>
{% endblock %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="your_website_domain/css_root/flaticon.css">	
    <title>Document</title>
</head>
<body>
    
    <div class="container">
        <!--{# if user.is_authenticated #}-->
        <!--    <h1>-->
        <!--        안녕, {{ user.username }}-->
        <!--        <a href="{# url 'accounts:profile' user.pk #}">[내 프로필]</a>-->
        <!--        <a href="{# url 'accounts:logout' #}">[로그아웃]</a>-->
        <!--    </h1>-->
        <!--{# else #}-->
        <!--    <h1>-->
        <!--        <a href="{# url 'accounts:login' #}">로그인</a>-->
        <!--        <a href="{# url 'accounts:signup' #}">회원가입</a>-->
        <!--    </h1>-->
        <!--{# endif #}-->
        <!--<hr>-->
        {% block body %}
        {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>비밀번호 변경</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원 수정</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% load gravatar %}
{% block body %}
<body style="background-color: #edeff2">
</body>

<nav class="navbar fixed-top navbar-light navbar-expand-md bg-faded d-flex justify-content-around bg-white">
<!--<nav class="navbar navbar-light fixed-top navbar-expand-md bg-faded d-flex justify-content-around">-->
    <div class="container">
        <i class="fab fa-instagram"></i>
        <a href="/" class="navbar-brand d-flex w-50 mr-auto"> Instagram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
            <ul class="navbar-nav w-100 d-flex justify-content-around">
                <li class="nav-item active">
                    <a class="nav-link" href="#">검색</a>
                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
                <li class="nav-item">
                    <!--<span class="badge badge-primary">Primary</span>-->
                    <a class="nav-link" href="#"><span class="badge badge-primary">로그인</span></a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link text-primary">가입하기</a>
                    <!--<a class="nav-link primary" href="#">Right</a>-->
                </li>
            </ul>
        </div>
    </div>
</nav>
<hr>
<img src="https://s.gravatar.com/avatar/{{ user_info.email|makemd5 }}?s=150" alt="profile" class="rounded-circle"/>
<h2>{{ user_info.username }}의 프로필</h2>
{% if user == user_info %}
<div>
    <a href="{% url 'accounts:edit' %}">[내 정보 수정]</a>
    <a href="{% url 'accounts:change_password' %}">[비밀번호 변경]</a>
    <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??');" >
       {% csrf_token %}
       <input type="submit" value="회원탈퇴"/>
    </form>
</div>
{% endif %}
<hr>


<div class="container">
    <div class="row">
        {% for board in user_info.board_set.all %}
        <div class="card  col-4" style="width: 18rem;">
          <img src="https://s.gravatar.com/avatar/{{ user_info.email|makemd5 }}?s=150" class="card-img-top" alt="dog">
          <div class="card-body">
            <h5 class="card-title">{{ board.title }}</h5>
            <p class="card-text">{{ board.content }}</p>
            <a href="{% url 'boards:detail' board.pk %}" class="btn btn-primary">게시글로 가기</a>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

<hr>
<h4>내가 쓴 댓글</h4>
<div class="row">
    
    {% for comment in user_info.comment_set.all %}
    <div class="col-12">
        <a href="{% url 'boards:detail' comment.board.pk %}">{{ comment.board }}글</a>의 댓글
        <p>{{ comment.content }}</p>
        <hr>
    </div>
    {% endfor %}
    
</div>




<!--<h3>{{ user_info.username }}가 작성한 게시글</h3>-->
<!--{# for board in user_info.board_set.all #}-->
<!--<p>제목 : <a href="{# url 'boards:detail' board.id #}">{{ board.title }}</a></p>-->
<!--<p>내용 : {{ board.content }}</p>-->
<!--<p>달린 댓글 수 : {{ board.comment_set.count }}</p>-->
<!--<hr>-->
<!--{# endfor #}-->
<!--<hr>-->
<!--<h3>{{ user_info.username }}가 작성한 댓글</h2>-->
<!--{# for comment in user_info.comment_set.all #}-->
<!--<p><a href="{# url 'boards:detail' comment.board.id #}">{{ comment.board }}글</a>의 댓글 / {{ comment.content }}</p>-->
<!--{# endfor #}-->

<!--<footer class="page-footer font-small indigo fixed-bottom">-->
<!--    <div class="container">-->
<!--        <a><i class="fab fa-instagram fa-4x"></i>instagram에 로그인</a>-->
<!--    </div>-->
    <!--<div class="footer-copyright text-center py-3">© 2018 Copyright:-->
<!--      <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>-->
<!--    </div>-->
<!--</footer>-->



<div class="card-footer fixed-bottom" style="height: 112px; opacity: 0.4;">
    <div class="container">
        <a><i class="fab fa-instagram fa-4x"></i>instagram에 로그인</a>
        <div>로그인하여 친구들의 사진과 동영상을 확인하고 회원님이 좋아할 만한 계정을 찾아보세요.</div>
    </div>
</div>



{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}